# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-12 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170912_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
